---
- name: Ensure ansible group exists
  ansible.builtin.group:
    state: present
    name: ansible
    gid: "{{ common_gid_ansible }}"
    system: true

- name: Ensure ansible user exists
  ansible.builtin.user:
    state: present
    name: ansible
    uid: "{{ common_uid_ansible }}"
    comment: Ansible user
    group: ansible
    groups: ssh
    system: true
    create_home: true
    home: /var/lib/ansible
    password: '!'
    shell: /bin/bash

- name: Ensure ansible ssh keys
  ansible.posix.authorized_key:
    state: "present"
    user: "ansible"
    key: "{{ item }}"
  loop: "{{ common_ansible_ssh_authorized_keys }}"

- name: Ensure ansible sudo rule is present
  community.general.sudoers:
    name: ansible
    state: present
    user: ansible
    nopassword: true
    commands: ALL

...
