---
- name: Ensure cloud-init is removed
  ansible.builtin.package:
    name: cloud-init
    state: absent
- name: Ensure basic packages are installed (Debian)
  ansible.builtin.package:
    name:
      - apt-file
      - bc
      - curl
      - dnsutils
      - ethtool
      - htop
      - httpie
      - iftop
      - iotop
      - iperf3
      - jq
      - ncdu
      - net-tools
      - nmap
      - psmisc
      - ripgrep
      - silversearcher-ag
      - sudo
      - sysstat
      - tar
      - tcpdump
      - telnet
      - tmux
      - tree
      - unzip
      - vim
      - wget
      - xz-utils
    state: present
  when: ansible_distribution == 'Debian'
- name: Ensure basic packages are installed (ArchLinux)
  ansible.builtin.package:
    name:
      - bash-completion
      - bc
      - curl
      - dnsutils
      - ethtool
      - htop
      - httpie
      - iftop
      - inetutils
      - inetutils
      - iotop
      - iperf3
      - jq
      - less
      - ncdu
      - net-tools
      - nmap
      - psmisc
      - ripgrep
      - sed
      - sudo
      - sysstat
      - tar
      - tcpdump
      - the_silver_searcher
      - tmux
      - tree
      - unzip
      - vim
      - wget
      - xz
    state: present
  when: ansible_distribution == 'Archlinux'

...
