---
- name: Ensure sshd-banner is installed
  ansible.builtin.copy:
    src: sshd-banner
    dest: /etc/ssh/sshd-banner
    mode: u=rw,g=r,o=r

- name: Set sshd config file
  ansible.builtin.template:
    src: templates/sshd.conf.j2
    dest: /etc/ssh/sshd_config
    mode: u=rw,g=r,o=r
  notify: Reload sshd service

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure sshd is running
  ansible.builtin.service:
    name: sshd.service
    state: started
    enabled: true
...
