---
- name: Ensure isc-dhcp-client is removed
  ansible.builtin.package:
    name: isc-dhcp-client
    state: absent
- name: Ensure isc-dhcp-common is removed
  ansible.builtin.package:
    name: isc-dhcp-common
    state: absent
- name: Ensure dhclient is removed
  ansible.builtin.package:
    name: dhclient
    state: absent
- name: Set /etc/systemd/networkd.conf config
  ansible.builtin.copy:
    src: networkd.conf
    dest: /etc/systemd/networkd.conf
    mode: 'u=rw,g=r,o=r'
  notify: Reload systemd-networkd service
- name: Ensure network configuration is present
  ansible.builtin.template:
    src: interface.network.j2
    dest: "/etc/systemd/network/20-{{ item.interface_name }}.network"
    owner: root
    group: root
    force: true
    mode: 'u=rw,g=r,o=r'
  loop: "{{ common_interfaces }}"
  notify: Reload systemd-networkd service
- name: Ensure systemd-networkd is running
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: systemd-networkd
- name: Ensure Debian networking is disabled
  ansible.builtin.systemd:
    enabled: false
    name: networking
  when: ansible_distribution == 'Debian'
- name: Ensure ifupdown is removed
  ansible.builtin.package:
    name: ifupdown
    state: absent

...
