---
- name: Ensure systemd-timesyncd is installed
  ansible.builtin.package:
    state: present
    name: systemd-timesyncd
  when: ansible_distribution == 'Debian'
- name: Set /etc/systemd/timesyncd.conf config
  ansible.builtin.copy:
    src: timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
  notify: Reload systemd-timesyncd service
- name: Ensure systemd-timesyncd is running
  ansible.builtin.service:
    name: systemd-timesyncd.service
    state: started
    enabled: true
...