---
- name: Ensure /var/log/journal exists
  ansible.builtin.file:
    state: directory
    path: /var/log/journal
    owner: root
    group: systemd-journal
    mode: 02755
- name: Set /etc/systemd/journald.conf config
  ansible.builtin.copy:
    src: journald.conf
    dest: /etc/systemd/journald.conf
    mode: 'u=rw,g=r,o=r'
  notify: Reload systemd-journald service
- name: Ensure systemd-journald is running
  ansible.builtin.service:
    name: systemd-journald.service
    state: started
    enabled: true

...
