---
- name: Reload sshd service
  ansible.builtin.systemd:
    name: sshd.service
    state: restarted
- name: Reload systemd-networkd service
  ansible.builtin.systemd:
    name: systemd-networkd.service
    state: restarted
- name: Reload systemd-journald service
  ansible.builtin.systemd:
    name: systemd-journald.service
    state: restarted
- name: Reload systemd-resolved service
  ansible.builtin.systemd:
    name: systemd-resolved.service
    state: restarted
- name: Reload systemd-timesyncd service
  ansible.builtin.systemd:
    name: systemd-timesyncd.service
    state: restarted
...